### ISSUE TITLE
Resposta Argumento Válido quando premissas são falsas

### ISSUE THREAD

**Issue by adolfont** [micalevisk/TruthTableGenerator-plus#1]
OI Micael,

Muito boa esta sua versão do gerador de tabelas-verdade do Michael Rieppel! Gostei bastante e recomendei a meus estudantes.

Não seria interessante que para esta entrara:
`(p&~p), p>q, q>r : r`
a página escrevesse "Argumento Válido"?

Att.
Adolfo

**Comment by micalevisk** [comment]
pra ser sincero, faz tanto tempo que adicionei isso no código que eu nem sei dizer o motivo de
`p>q, q>r : r`
mostrar _argumento inválido_ mas pra essa tua entrada, não :thinking:

**Comment by adolfont** [comment]
O meu exemplo é consequência lógica e o seu não é. Acho que você não escreveu "argumento válido" pois nenhuma linha satisfaz todas as premissas. Sabe indicar em que linha isto é feito?

**Comment by micalevisk** [comment]
https://github.com/micalevisk/TruthTableGenerator-plus/blob/81563cf4c555f0797791ec9514821ff875a02a55/truthtable.js#L212

https://github.com/micalevisk/TruthTableGenerator-plus/blob/81563cf4c555f0797791ec9514821ff875a02a55/truthtable.js#L126-L140

**Comment by adolfont** [comment]
Entendi. Então o problema está em 
https://github.com/micalevisk/TruthTableGenerator-plus/blob/81563cf4c555f0797791ec9514821ff875a02a55/truthtable.js#L135

Se a quantidade de linhas críticas for 0, a conclusão é **consequência lógica** das premissas.

**Comment by micalevisk** [comment]
se quiser abrir um PR pra corrigir isso, fique a vontade :smiley:

**Comment by adolfont** [comment]
Feito.
